### ISSUE TITLE
default make example results in DRC errors

### ISSUE THREAD

**Issue by mattvenn** [jazvw/chip_art#3]
![image](https://user-images.githubusercontent.com/634220/173245293-5a224ffc-2ae6-4b84-abd5-84ea8a22d90a.png)

would be smooth if the default passed precheck

**Comment by jazvw** [comment]
Ya, that would be nice wouldn't it :) Could you see if it passes with the text removed from the input png?

**Comment by jazvw** [comment]
Fixed in latest
